language: node_js
node_js: node
script:
  - yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: docs/.vuepress/dist
  keep-history: true
  on:
    branch: source
  target-branch: master