language: node_js
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: docs/.vuepress/dist
  keep-history: true
  on:
    branch: master
